name: Get and Cache Dependencies
description: Get and cache dependencies for a Node.js project
inputs:
  caching:
    description: 'Set false to disable caching'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: 'True if cache was hit'
    value: 'testting output'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run:  | 
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash # shell key required for composite actions if run is specified
